package team.hyznrj.esgsmanager.entity;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminId
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private Long adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPhone
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String adminphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminEmail
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String adminemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminAccount
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String adminaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPassword
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String adminpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private Integer adminstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminJurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String adminjurisdiction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminId
     *
     * @return the value of admin.adminId
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public Long getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminId
     *
     * @param adminid the value for admin.adminId
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setAdminid(Long adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminName
     *
     * @return the value of admin.adminName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminName
     *
     * @param adminname the value for admin.adminName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPhone
     *
     * @return the value of admin.adminPhone
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getAdminphone() {
        return adminphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPhone
     *
     * @param adminphone the value for admin.adminPhone
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setAdminphone(String adminphone) {
        this.adminphone = adminphone == null ? null : adminphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminEmail
     *
     * @return the value of admin.adminEmail
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getAdminemail() {
        return adminemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminEmail
     *
     * @param adminemail the value for admin.adminEmail
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setAdminemail(String adminemail) {
        this.adminemail = adminemail == null ? null : adminemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminAccount
     *
     * @return the value of admin.adminAccount
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getAdminaccount() {
        return adminaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminAccount
     *
     * @param adminaccount the value for admin.adminAccount
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setAdminaccount(String adminaccount) {
        this.adminaccount = adminaccount == null ? null : adminaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPassword
     *
     * @return the value of admin.adminPassword
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getAdminpassword() {
        return adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPassword
     *
     * @param adminpassword the value for admin.adminPassword
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setAdminpassword(String adminpassword) {
        this.adminpassword = adminpassword == null ? null : adminpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminStatus
     *
     * @return the value of admin.adminStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public Integer getAdminstatus() {
        return adminstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminStatus
     *
     * @param adminstatus the value for admin.adminStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setAdminstatus(Integer adminstatus) {
        this.adminstatus = adminstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminJurisdiction
     *
     * @return the value of admin.adminJurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getAdminjurisdiction() {
        return adminjurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminJurisdiction
     *
     * @param adminjurisdiction the value for admin.adminJurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setAdminjurisdiction(String adminjurisdiction) {
        this.adminjurisdiction = adminjurisdiction == null ? null : adminjurisdiction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminid=").append(adminid);
        sb.append(", adminname=").append(adminname);
        sb.append(", adminphone=").append(adminphone);
        sb.append(", adminemail=").append(adminemail);
        sb.append(", adminaccount=").append(adminaccount);
        sb.append(", adminpassword=").append(adminpassword);
        sb.append(", adminstatus=").append(adminstatus);
        sb.append(", adminjurisdiction=").append(adminjurisdiction);
        sb.append("]");
        return sb.toString();
    }
}