package team.hyznrj.esgsmanager.entity;

import java.util.Date;

public class Bulletin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bulletin.bulletinId
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private Long bulletinid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bulletin.bulletinType
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String bulletintype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bulletin.bulletinTypePath
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String bulletintypepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bulletin.adminName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bulletin.bulletinCreateTime
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private Date bulletincreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bulletin.bulletinEditTime
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private Date bulletinedittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bulletin.bulletinStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private Integer bulletinstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bulletin.bulletinId
     *
     * @return the value of bulletin.bulletinId
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public Long getBulletinid() {
        return bulletinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bulletin.bulletinId
     *
     * @param bulletinid the value for bulletin.bulletinId
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setBulletinid(Long bulletinid) {
        this.bulletinid = bulletinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bulletin.bulletinType
     *
     * @return the value of bulletin.bulletinType
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getBulletintype() {
        return bulletintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bulletin.bulletinType
     *
     * @param bulletintype the value for bulletin.bulletinType
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setBulletintype(String bulletintype) {
        this.bulletintype = bulletintype == null ? null : bulletintype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bulletin.bulletinTypePath
     *
     * @return the value of bulletin.bulletinTypePath
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getBulletintypepath() {
        return bulletintypepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bulletin.bulletinTypePath
     *
     * @param bulletintypepath the value for bulletin.bulletinTypePath
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setBulletintypepath(String bulletintypepath) {
        this.bulletintypepath = bulletintypepath == null ? null : bulletintypepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bulletin.adminName
     *
     * @return the value of bulletin.adminName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bulletin.adminName
     *
     * @param adminname the value for bulletin.adminName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bulletin.bulletinCreateTime
     *
     * @return the value of bulletin.bulletinCreateTime
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public Date getBulletincreatetime() {
        return bulletincreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bulletin.bulletinCreateTime
     *
     * @param bulletincreatetime the value for bulletin.bulletinCreateTime
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setBulletincreatetime(Date bulletincreatetime) {
        this.bulletincreatetime = bulletincreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bulletin.bulletinEditTime
     *
     * @return the value of bulletin.bulletinEditTime
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public Date getBulletinedittime() {
        return bulletinedittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bulletin.bulletinEditTime
     *
     * @param bulletinedittime the value for bulletin.bulletinEditTime
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setBulletinedittime(Date bulletinedittime) {
        this.bulletinedittime = bulletinedittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bulletin.bulletinStatus
     *
     * @return the value of bulletin.bulletinStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public Integer getBulletinstatus() {
        return bulletinstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bulletin.bulletinStatus
     *
     * @param bulletinstatus the value for bulletin.bulletinStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setBulletinstatus(Integer bulletinstatus) {
        this.bulletinstatus = bulletinstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bulletinid=").append(bulletinid);
        sb.append(", bulletintype=").append(bulletintype);
        sb.append(", bulletintypepath=").append(bulletintypepath);
        sb.append(", adminname=").append(adminname);
        sb.append(", bulletincreatetime=").append(bulletincreatetime);
        sb.append(", bulletinedittime=").append(bulletinedittime);
        sb.append(", bulletinstatus=").append(bulletinstatus);
        sb.append("]");
        return sb.toString();
    }
}