package team.hyznrj.esgsmanager.entity;

public class JurisdictionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.jurisdictionName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String jurisdictionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.finenessName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String finenessname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.jurisdictionName
     *
     * @return the value of jurisdiction.jurisdictionName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getJurisdictionname() {
        return jurisdictionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.jurisdictionName
     *
     * @param jurisdictionname the value for jurisdiction.jurisdictionName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setJurisdictionname(String jurisdictionname) {
        this.jurisdictionname = jurisdictionname == null ? null : jurisdictionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.finenessName
     *
     * @return the value of jurisdiction.finenessName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getFinenessname() {
        return finenessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.finenessName
     *
     * @param finenessname the value for jurisdiction.finenessName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setFinenessname(String finenessname) {
        this.finenessname = finenessname == null ? null : finenessname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jurisdictionname=").append(jurisdictionname);
        sb.append(", finenessname=").append(finenessname);
        sb.append("]");
        return sb.toString();
    }
}