package team.hyznrj.esgsmanager.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPhone
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userEmail
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String useremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAccount
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String useraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPassword
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private Integer userstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userSeniorMemberStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private Integer userseniormemberstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userSeniorMemberCreateDate
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    private Date userseniormembercreatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userid the value for user.userId
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param username the value for user.userName
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPhone
     *
     * @return the value of user.userPhone
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPhone
     *
     * @param userphone the value for user.userPhone
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userEmail
     *
     * @return the value of user.userEmail
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userEmail
     *
     * @param useremail the value for user.userEmail
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAccount
     *
     * @return the value of user.userAccount
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getUseraccount() {
        return useraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAccount
     *
     * @param useraccount the value for user.userAccount
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setUseraccount(String useraccount) {
        this.useraccount = useraccount == null ? null : useraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPassword
     *
     * @return the value of user.userPassword
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPassword
     *
     * @param userpassword the value for user.userPassword
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userStatus
     *
     * @return the value of user.userStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public Integer getUserstatus() {
        return userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userStatus
     *
     * @param userstatus the value for user.userStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setUserstatus(Integer userstatus) {
        this.userstatus = userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userSeniorMemberStatus
     *
     * @return the value of user.userSeniorMemberStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public Integer getUserseniormemberstatus() {
        return userseniormemberstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userSeniorMemberStatus
     *
     * @param userseniormemberstatus the value for user.userSeniorMemberStatus
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setUserseniormemberstatus(Integer userseniormemberstatus) {
        this.userseniormemberstatus = userseniormemberstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userSeniorMemberCreateDate
     *
     * @return the value of user.userSeniorMemberCreateDate
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public Date getUserseniormembercreatedate() {
        return userseniormembercreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userSeniorMemberCreateDate
     *
     * @param userseniormembercreatedate the value for user.userSeniorMemberCreateDate
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    public void setUserseniormembercreatedate(Date userseniormembercreatedate) {
        this.userseniormembercreatedate = userseniormembercreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", userphone=").append(userphone);
        sb.append(", useremail=").append(useremail);
        sb.append(", useraccount=").append(useraccount);
        sb.append(", userpassword=").append(userpassword);
        sb.append(", userstatus=").append(userstatus);
        sb.append(", userseniormemberstatus=").append(userseniormemberstatus);
        sb.append(", userseniormembercreatedate=").append(userseniormembercreatedate);
        sb.append("]");
        return sb.toString();
    }
}