package team.hyznrj.esgsmanager.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.hyznrj.esgsmanager.entity.Bulletin;
import team.hyznrj.esgsmanager.entity.BulletinExample;

public interface BulletinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int countByExample(BulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int deleteByExample(BulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int deleteByPrimaryKey(Long bulletinid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int insert(Bulletin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int insertSelective(Bulletin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    List<Bulletin> selectByExample(BulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    Bulletin selectByPrimaryKey(Long bulletinid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") Bulletin record, @Param("example") BulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int updateByExample(@Param("record") Bulletin record, @Param("example") BulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int updateByPrimaryKeySelective(Bulletin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int updateByPrimaryKey(Bulletin record);
}