package team.hyznrj.esgsmanager.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.hyznrj.esgsmanager.entity.JurisdictionExample;
import team.hyznrj.esgsmanager.entity.JurisdictionKey;

public interface JurisdictionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int countByExample(JurisdictionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int deleteByExample(JurisdictionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int deleteByPrimaryKey(JurisdictionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int insert(JurisdictionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int insertSelective(JurisdictionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    List<JurisdictionKey> selectByExample(JurisdictionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") JurisdictionKey record, @Param("example") JurisdictionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Wed Dec 27 09:21:05 CST 2017
     */
    int updateByExample(@Param("record") JurisdictionKey record, @Param("example") JurisdictionExample example);
}